hashmap.c
check_init
void update_load_factor(hmap_t *self)
References hashmap_container::current_load, hashmap_container::len, hashmap_container::set.
Referenced by hashmap_set.
size_t make_index(size_t mod, uint64_t nonce, rt_buff_t *key)
References rt_buff_borrow, rt_buff_sizeof.
Referenced by hashmap_evict, hashmap_get, hashmap_set.
hmap_t* hashmap_new(size_t init_len, uint8_t *nonce, uint32_t load_lim, uint8_t expand_factor)
Initialize a new hashmap with the options defined here, check the struct hashmap_container for details on what each one does.
init_len How many nodes worth of space to pre-allocate nonce Append 64 bytes of this value to keys before hashing, if null nothing is appended. load_lim Maximum load factor (used slots/currently allocated) before triggering expansion. expand_factor When expansion is triggered expand by this factor, recommended is 2. A newly initialized hashmap configured with the received parameters
References hashmap_container::current_load, hashmap_node::data, hashmap_container::data, hashmap_container::expand_factor, hashmap_container::expand_trig, hashmap_node::key, hashmap_container::len, hashmap_container::no_expand_auto, hashmap_container::nonce, hashmap_node::reclaim, hashmap_container::set.
int32_t hashmap_set(hmap_t *self, rt_buff_t *key, void *value)
Set the key to value on self.
self The hashmap to set the key on key A rt_buff to use as a key value Pointer to any value 0 on success 1 otherwise
References hashmap_node::data, hashmap_container::data, hashmap_node::key, hashmap_container::len, make_index, hashmap_container::nonce, hashmap_node::reclaim, rt_buff_borrow, hashmap_container::set, update_load_factor.
void* hashmap_get(hmap_t *self, rt_buff_t *key)
self The hashmap to operate on key A rt_buff to use as a key
References hashmap_node::data, hashmap_container::data, hashmap_node::key, hashmap_container::len, make_index, hashmap_container::nonce, hashmap_node::reclaim.
void* hashmap_evict(hmap_t *self, rt_buff_t *key)
Mark a node for reuse, and return the value that was stored in it.
self The hashmap to operate on key A rt_buff to use as a key The value held in the key previously
References hashmap_node::data, hashmap_container::data, hashmap_container::len, make_index, hashmap_container::nonce, hashmap_node::reclaim.
void hashmap_free(hmap_t *self)
Release the memory associated to a hashmap and it's nodes.
self The hashmap to destroy
References hashmap_container::data, hashmap_node::key, hashmap_container::len, rt_buff_free, rt_buff_return.