linked_list.c
ll_check_init
ll_node_t* new_ll_node(void *val)
References singly_linked_list_node::dt_ptr, singly_linked_list_node::next.
Referenced by ll_add_node, ll_new.
dll_node_t* new_dll_node(void *val)
References doubly_linked_list_node::dt_ptr, doubly_linked_list_node::next, doubly_linked_list_node::prev.
int32_t ll_insert_at(ll_t *self, ll_node_t *new_node, size_t pos)
References linked_list::first, linked_list::len, singly_linked_list_node::next.
Referenced by ll_add_node.
ll_t* ll_new(void *fval)
Initialize a new singly linked list, you can set all the parameters bellow to create an empty list.
fval Pointer to the value of the first node. A new linked, possibly initialized with a first node.
References linked_list::first, linked_list::last, linked_list::len, new_ll_node.
int32_t ll_add_node(ll_t *self, void *val, enum LL_ADD_OP op, size_t pos)
Add a new node created from the parameters to the linked list.
val_sz and val_isz exist as a convenience, they are free to be used in application specific ways. self The linked list to change val The value to assign the list node op Where to insert the node, if not set to INSERT pos is ignored pos If op is INSERT where to insert the node in the list 0 on success, -1 otherwise
References linked_list::first, linked_list::last, linked_list::len, LL_APPEND, LL_INSERT, ll_insert_at, LL_PREPEND, new_ll_node, singly_linked_list_node::next.
void ll_free(ll_t *self)
References linked_list::first, linked_list::len, singly_linked_list_node::next.