rt_buffer.h
_RTHOST_STRING_
Strings that are more than a byte array.
Matheus Xavier <mxavier[AT]neonimp.com>
typedef struct managed_buffer rt_buff_t
rt_buff_t* rt_buff_new(uint8_t *value, size_t val_len)
Create a new managed string from a buffer of bytes.
value Buffer to initialize the managed string with. val_len Length of the buffer value. A pointer to an initialized rt_buff_t instance.
References managed_buffer::data, managed_buffer::len, managed_buffer::lock, managed_buffer::needs_sync, managed_buffer::ref_ct.
const char* rt_buff_borrow(rt_buff_t *self)
Get a reference to the underlying buffer of a managed string to use with functions that need a raw const char pointer.
Never pass this pointer to a function that modifies the buffer in place, as this cause for UNDEFINED BEHAVIOUR, since the properties of the buffer are tracked by the internal state. self Reference to the managed string. A reference to the underlying buffer.
References managed_buffer::data, managed_buffer::lock, managed_buffer::ref_ct.
Referenced by hashmap_set, make_index.
char* rt_buff_borrow_writable(rt_buff_t *self)
Get a write-able reference to the underlying buffer of a managed string to use with functions that need a raw const char pointer, note that the write-able reference MUST BE the only reference, this function will fail if ANY of the following is true: There is already ANY references to the buffer leased out. There is a lock on the string.
Never pass this pointer to a function that modifies the buffer in place, as this cause for UNDEFINED BEHAVIOUR, since the properties of the buffer are tracked by the internal state. self Reference to the managed string. A reference to the underlying buffer.
References managed_buffer::data, managed_buffer::lock, managed_buffer::needs_sync, managed_buffer::ref_ct.
void rt_buff_return(rt_buff_t *self)
Returns a borrowed reference to the underlying buffer and decreases the reference counter.
self Reference to the managed string.
References managed_buffer::lock, managed_buffer::needs_sync, managed_buffer::ref_ct.
Referenced by hashmap_free, rt_buff_free.
size_t rt_buff_sizeof(const rt_buff_t *self)
Get the size of the underlying buffer.
self Buffer to get the size of
References managed_buffer::len.
Referenced by make_index.
uint64_t rt_buff_free(rt_buff_t *self)
Destroys a managed string if it's reference counter is 0, and there is no lock on it, do not use a reference to a string passed to this function after calling it.
self The string to attempt destruction on. 0 if the string was deallocated successfully or the refcount otherwise, check the result!.
References managed_buffer::data, managed_buffer::lock, managed_buffer::ref_ct, rt_buff_return.
Referenced by hashmap_free.